openapi: 3.0.3
info:
  title: Emoji Cipher API
  description: API for encrypting and decrypting text using emoji ciphers.
  version: 1.0.0
servers:
  - url: https://cipher.api.webally.co.za/
paths:
  /encrypt:
    post:
      operationId: encryptText
      summary: Encrypt text
      description: Encrypts plain text into emoji cipher text.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptRequest'
      responses:
        '200':
          description: Successfully encrypted text.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptResponse'
        '400':
          description: Bad request (missing 'text' in request body).
        '401':
          description: Unauthorized access (missing or invalid API key).
      security:
        - ApiKeyAuth: []
          scheme: bearer
          bearerFormat: Authorization

  /decrypt:
    post:
      operationId: decryptText
      summary: Decrypt text
      description: Decrypts emoji cipher text back into plain text.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecryptRequest'
      responses:
        '200':
          description: Successfully decrypted text.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecryptResponse'
        '400':
          description: Bad request (missing 'encrypted_text' in request body).
        '401':
          description: Unauthorized access (missing or invalid API key).
      security:
        - ApiKeyAuth: []
          scheme: bearer
          bearerFormat: Authorization
  /privacy-policy:
    get:
      operationId: privacyPolicy
      summary: Privacy Policy
      description: Returns the privacy policy in HTML format.
      responses:
        '200':
          description: Successfully retrieved privacy policy.
          content:
            text/html:
              schema:
                type: string
        '404':
          description: Privacy policy not found.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    EncryptRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: Plain text to be encrypted.
    EncryptResponse:
      type: object
      properties:
        encrypted_text:
          type: string
          description: Encrypted text using emojis.
    DecryptRequest:
      type: object
      required:
        - encrypted_text
      properties:
        encrypted_text:
          type: string
          description: Emoji cipher text to be decrypted.
    DecryptResponse:
      type: object
      properties:
        text:
          type: string
          description: Decrypted plain text.
security:
  - ApiKeyAuth: []
